apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: polaris-system
data:
  mesh: |-
    defaultConfig:

      # service sync mode: all, demand
      serviceSyncMode: "all"

      proxyMetadata:
        polarisServerAddress: "polaris-server address"
        clusterName: "default"
        polarisAccessToken: "<if polaris open auth, need to set the authentication token>"