apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: polaris-system
data:
  mesh: |-
    # k8s cluster name
    clusterName: "default"
    # polaris-access-token 北极星开启鉴权时需要配置
    accessToken: ""
    # service sync
    serviceSync:
      mode: "all"
      serverAddress: "polaris-server address"
    defaultConfig:
      proxyMetadata:
        serverAddress: "polaris-server address"