apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: polaris-system
data:
  mesh: |-
    defaultConfig:

      # Envoy proxy port to listen on for the admin interface.
      proxyAdminPort: 15000

      proxyMetadata:
        POLARIS_SERVER_URL: "polaris-server-address-here"
        CLUSTER_NAME: "default"