apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    qcloud-app: polaris-controller
  name: polaris-controller
  namespace: operator
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: polaris-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: polaris-controller
      annotations:
        tke.cloud.tencent.com/vpc-eni-cni-ip: "true"
    spec:
      containers:
        - name: polaris-controller
          image: csighub.tencentyun.com/library/polaris-controller:v0.3
          command: ["./polaris-controller"]
          args: ["--min-resync-period=60s",
                 "--v=4",
                 "--cluster-name=$(EKS_CLUSTER_ID)",
                 "--leader-elect-namespace=operator",
                 "--concurrency-polaris-size=100"
          ]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /polaris-controller/log
              name: log
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: polaris-controller
      volumes:
        - hostPath:
            path: /data/polaris-controller/log
            type: "DirectoryOrCreate"
          name: log