apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    qcloud-app: polaris-controller
  name: polaris-controller
  namespace: polaris-system
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: polaris-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: polaris-controller
        app: sidecar-injector
    spec:
      containers:
        - name: polaris-controller
          image: ccr.ccs.tencentyun.com/polaris_mesh/polaris-controller:v1.1.0
          command: ["./polaris-controller"]
          args: ["--min-resync-period=60s",
                 "--v=4",
                 "--cluster-name=default",
                 "--leader-elect-namespace=polaris-system",
                 "--concurrency-polaris-size=100",
                 "--sync-mode=ALL",
                 "--stderrthreshold=0",
                 "--log-dir=/polaris-controller/log",
                 "--log-file=/polaris-controller/log/test.log",
                 "--logtostderr=false",
                 "--log-file-max-size=1800",
                 "--leader-elect=true"
          ]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /polaris-controller/log
              name: log
            - name: certs
              mountPath: /etc/polaris-inject/certs
              readOnly: true
            - name: inject-config
              mountPath: /etc/polaris-inject/inject
              readOnly: true
            - name: config-volume
              mountPath: /etc/polaris-inject/config
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: polaris-controller
      volumes:
        - name: certs
          secret:
            secretName: polaris-sidecar-injector
        - name: inject-config
          configMap:
            name: polaris-sidecar-injector
            items:
              - key: config
                path: config
              - key: values
                path: values
        - name: config-volume
          configMap:
            name: injector-mesh
        - hostPath:
            path: /data/polaris-controller/log
            type: "DirectoryOrCreate"
          name: log